"""The redesigned monitor: numerics, alarms on screen, display controls, CPR,
scenarios and the event log - driven through the real window.

Signal is generated by running the engine straight into the ring buffer, so a
test can put 30 seconds of any rhythm on screen in a fraction of a second, then
call the window's own update tick.

Run directly (``python tests/test_monitor_ui.py``) or under pytest.
"""

from __future__ import annotations

import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PyQt6.QtWidgets import QApplication                          # noqa: E402

from core.alarms import HIGH, MEDIUM, Alarm, AlarmLimits, AlarmTracker   # noqa: E402
from core.buffer import RingBuffer                                 # noqa: E402
from core.generator import SignalGenerator                         # noqa: E402
from core.scenarios import SCENARIOS                               # noqa: E402
from core.state import SimulationState                             # noqa: E402
from core.vitals import Vitals                                     # noqa: E402
from ui import icons                                               # noqa: E402
from ui.main_window import MainWindow                              # noqa: E402
from ui.monitor import ECG_RANGE, MonitorView                      # noqa: E402

APP = QApplication.instance() or QApplication(sys.argv[:1])


def live(seconds: float = 30.0, **params):
    """A bound window whose buffer already holds ``seconds`` of the given patient."""
    state = SimulationState(**params)
    buffer = RingBuffer()
    generator = SignalGenerator(state, buffer, rng=np.random.default_rng(5))
    window = MainWindow(state.snapshot())
    window.bind(state, buffer, generator)
    run(window, seconds)
    return window, state, generator


def run(window: MainWindow, seconds: float) -> None:
    """Advance the simulation, ticking the window every half second as it would."""
    generator, buffer = window._generator, window._buffer
    for i in range(int(seconds * 20)):
        buffer.write(generator.engine.next_chunk(50))
        if i % 10 == 9:
            window.refresh_vitals()


# --- numerics on screen ---------------------------------------------------------
def test_tiles_show_what_was_measured():
    # Pressure targets are calibrated at the reference 72 bpm; at any other rate
    # the arterial line legitimately reads something else (see the next test).
    window, _, _ = live(heart_rate=72, systolic=130, diastolic=85, spo2_target=95)
    try:
        m = window.monitor
        assert abs(int(m.hr_tile.value_text) - 72) <= 3
        assert m.spo2_tile.value_text == "95"
        sys_, dia = (int(x) for x in m.abp_tile.value_text.split("/"))
        assert abs(sys_ - 130) <= 4 and abs(dia - 85) <= 4
        assert m.rr_tile.value_text == "15"
    finally:
        window.close()


def test_a_faster_heart_raises_the_measured_pressure():
    slow, _, _ = live(heart_rate=72)
    fast, _, _ = live(heart_rate=110)
    try:
        mean = lambda w: int(w.monitor.abp_tile.sub_label.text().strip("()"))   # noqa: E731
        assert mean(fast) > mean(slow) + 5, (mean(slow), mean(fast))
    finally:
        slow.close()
        fast.close()


def test_tiles_read_the_rhythm_not_the_slider():
    window, _, _ = live(cardiac_rhythm="V-Tach", heart_rate=60)
    try:
        assert window.monitor.hr_tile.value_text == "160"
    finally:
        window.close()


def test_arrest_blanks_the_numerics_and_flags_them_in_words():
    window, _, _ = live(cardiac_rhythm="V-Fib")
    try:
        m = window.monitor
        assert m.hr_tile.value_text == "---"
        assert m.abp_tile.value_text.startswith("---")
        assert m.spo2_tile.value_text == "---"
        # Never colour alone: every flagged tile carries a text badge.
        assert m.hr_tile.badge.isVisibleTo(m.hr_tile) and m.hr_tile.badge.text()
        assert m.abp_tile.badge.text() == "NO PULSE"
    finally:
        window.close()


def test_a_healthy_patient_shows_no_badges():
    window, _, _ = live()
    try:
        for tile in window.monitor.tiles.values():
            assert tile.alarm_message is None, (tile.title.text(), tile.alarm_message)
    finally:
        window.close()


def test_limits_are_live():
    window, _, _ = live(heart_rate=100)
    try:
        assert window.monitor.hr_tile.alarm_message is None
        window.controls.limit_spins["hr_high"].setValue(90)
        assert window.limits.hr_high == 90
        run(window, 3.0)
        assert window.monitor.hr_tile.badge.text() == "▲ HIGH"
    finally:
        window.close()


def test_vital_alarms_can_be_switched_off():
    window, _, _ = live(resp_pattern="Apnoea")
    try:
        assert any(a.code == "apnoea" for a in window.physiological_alarms)
        window.controls.vital_alarm_check.setChecked(False)
        run(window, 1.0)
        assert window.physiological_alarms == []
    finally:
        window.close()


def test_a_vital_sign_emergency_reaches_the_banner():
    """Apnoea is not a rhythm, but it must not be confined to a tile."""
    window, _, _ = live(resp_pattern="Apnoea")
    try:
        window._refresh_alarm()
        assert window.alarm_banner.is_active
        assert window.alarm_banner.headline == "APNOEA"
    finally:
        window.close()


def test_rhythm_alarm_takes_precedence_on_the_banner():
    window, _, _ = live(cardiac_rhythm="V-Fib", resp_pattern="Apnoea")
    try:
        window._refresh_alarm()
        assert window.alarm_banner.headline == "VENTRICULAR FIBRILLATION"
    finally:
        window.close()


def test_acknowledge_stops_the_flashing():
    window, _, _ = live(resp_pattern="Apnoea")
    try:
        tile = window.monitor.rr_tile
        styles = set()
        for _ in range(4):
            window.refresh_vitals()
            styles.add(tile.styleSheet())
        assert len(styles) > 1, "a high-priority tile should flash"

        window.controls.acknowledge_button.click()
        styles = set()
        for _ in range(4):
            window.refresh_vitals()
            styles.add(tile.styleSheet())
        assert len(styles) == 1, "acknowledged alarm still flashing"
    finally:
        window.close()


# --- debouncing ---------------------------------------------------------------------
def test_tracker_ignores_blips_and_holds_through_dips():
    alarm = Alarm("hr_low", HIGH, "hr", "HR LOW 40")
    tracker = AlarmTracker(onset_s=1.0, clear_s=3.0)
    assert tracker.update([alarm], 0.0)[1] == []          # first sighting: pending
    assert tracker.update([], 0.5)[0] == []               # a blip: never raised
    tracker.update([alarm], 1.0)
    active, raised, _ = tracker.update([alarm], 2.0)
    assert raised == [alarm] and active == [alarm]
    assert tracker.update([], 2.5)[0] == [alarm], "a momentary dip must not clear it"
    _, _, cleared = tracker.update([], 5.1)
    assert cleared == [alarm]


def test_tracker_keeps_the_message_current():
    tracker = AlarmTracker(onset_s=0.0)
    tracker.update([Alarm("hr_high", MEDIUM, "hr", "HR HIGH 130")], 0.0)
    active, _, _ = tracker.update([Alarm("hr_high", MEDIUM, "hr", "HR HIGH 142")], 0.5)
    assert active[0].message == "HR HIGH 142"


def _alarm_entries(window: MainWindow) -> list[str]:
    return [m for m in window.controls.event_log.messages()
            if "Alarm:" in m or "Cleared:" in m]


def test_a_rate_sitting_on_its_limit_does_not_flood_the_log():
    """Respiratory sinus arrhythmia swings a 120 bpm rate either side of a
    120 bpm limit every breath.  Undebounced, that is an alarm and a clear
    every few seconds; the tracker has to absorb it.

    Compared against an undebounced run of the same patient, so the test fails
    if the scenario stops flapping - rather than passing because it never did.
    """
    def entries(tracker: AlarmTracker | None) -> list[str]:
        window, _, _ = live(12.0, heart_rate=120)
        try:
            window.controls.limit_spins["hr_high"].setValue(120)
            if tracker is not None:
                window.alarm_tracker = tracker
            window.controls.event_log.clear()
            run(window, 60.0)
            return _alarm_entries(window)
        finally:
            window.close()

    raw = entries(AlarmTracker(onset_s=0.0, clear_s=0.0))
    debounced = entries(None)
    assert len(raw) >= 10, f"scenario no longer flaps ({len(raw)} raw entries)"
    assert len(debounced) <= len(raw) // 4, f"{len(debounced)} vs {len(raw)} undebounced"


def test_cleared_alarms_are_logged_in_words_not_codes():
    window, state, _ = live(15.0, cardiac_rhythm="V-Fib")
    try:
        state.update(cardiac_rhythm="Sinus")
        window.controls.event_log.clear()
        run(window, 15.0)
        cleared = [m for m in _alarm_entries(window) if "Cleared:" in m]
        assert cleared, "recovering from VF should clear its alarms"
        assert not any("_" in m for m in cleared), f"internal codes leaked: {cleared}"
    finally:
        window.close()


# --- display controls -------------------------------------------------------------
def test_freeze_holds_the_picture_while_the_patient_continues():
    window, _, generator = live(10.0)
    try:
        window.monitor.refresh()
        before = window.monitor.ecg_curve.yData.copy()
        window.toggle_freeze()
        assert window.monitor.frozen and window.freeze_button.isChecked()
        run(window, 2.0)
        window.monitor.refresh()
        assert np.array_equal(before, window.monitor.ecg_curve.yData, equal_nan=True)
        assert window._buffer.total_written > 10_000, "simulation stopped with the display"

        window.toggle_freeze()
        window.monitor.refresh()
        assert not np.array_equal(before, window.monitor.ecg_curve.yData, equal_nan=True)
    finally:
        window.close()


def test_grid_toggle_stays_in_sync_everywhere():
    window = MainWindow()
    try:
        window.grid_button.click()
        assert window.monitor.grid_visible and window.controls.grid_switch.isChecked()
        window.controls.grid_switch.click()
        assert not window.monitor.grid_visible and not window.grid_button.isChecked()
    finally:
        window.close()


def test_gain_rescales_only_the_ecg():
    view = MonitorView()
    resp_before = view.resp_plot.getPlotItem().getViewBox().viewRange()[1]
    view.set_gain(2.0)
    low, high = view.ecg_plot.getPlotItem().getViewBox().viewRange()[1]
    assert abs(low - ECG_RANGE[0] / 2) < 1e-9 and abs(high - ECG_RANGE[1] / 2) < 1e-9
    assert view.resp_plot.getPlotItem().getViewBox().viewRange()[1] == resp_before


def test_pressure_scale_follows_the_target():
    view = MonitorView()
    view.set_abp_scale_for(190)
    assert view.abp_plot.getPlotItem().getViewBox().viewRange()[1][1] >= 210
    view.set_abp_scale_for(90)
    assert view.abp_plot.getPlotItem().getViewBox().viewRange()[1][1] == 120


def test_tick_labels_never_read_negative_zero():
    view = MonitorView()
    for name, plot in view.plots.items():
        labels = [t[1] for t in plot.getPlotItem().getAxis("left")._tickLevels[0]]
        assert "-0" not in labels, f"{name}: {labels}"
        assert len(labels) >= 3, f"{name} has too few ticks: {labels}"


# --- therapy ------------------------------------------------------------------------
def test_cpr_button_drives_the_state_and_follows_it_back():
    window, state, _ = live(5.0, cardiac_rhythm="Asystole")
    try:
        window.controls.cpr_button.click()
        assert state.snapshot().cpr_active
        assert "Stop" in window.controls.cpr_button.text()
        state.update(cpr_active=False)                    # e.g. a scenario reset
        window.controls.sync(state.snapshot())
        assert not window.controls.cpr_button.isChecked()
        assert "Start" in window.controls.cpr_button.text()
    finally:
        window.close()


def test_cpr_puts_a_pressure_on_the_screen():
    window, state, _ = live(15.0, cardiac_rhythm="V-Fib")
    try:
        assert window.monitor.abp_tile.value_text.startswith("---")
        window.controls.cpr_button.click()
        run(window, 12.0)
        assert not window.monitor.abp_tile.value_text.startswith("---")
    finally:
        window.close()


def test_shock_outcomes_are_logged():
    window, state, generator = live(5.0, cardiac_rhythm="V-Fib")
    try:
        window.controls.defib_button.click()
        run(window, 2.0)
        _, kind, outcome, rhythm = generator.engine.shock_log[-1]
        window._on_shock_delivered(kind, outcome, rhythm)
        assert any("Defibrillation" in m for m in window.controls.event_log.messages())
        assert window.controls.shock_label.text() != "No shocks delivered."
    finally:
        window.close()


# --- scenarios and log ---------------------------------------------------------------
def test_scenario_runs_from_the_panel():
    window, state, _ = live(5.0)
    try:
        c = window.controls
        c.scenario_list.setCurrentRow(list(SCENARIOS).index("Evolving heart block"))
        c.scenario_button.click()
        assert window.player.running
        assert window.scenario_chip.isVisibleTo(window)
        assert "Stop" in c.scenario_button.text() and not c.scenario_list.isEnabled()

        window.player._started -= 30.0                   # jump ahead in scenario time
        run(window, 1.0)
        assert state.snapshot().cardiac_rhythm == "Mobitz I (Wenckebach)"
        assert c.rhythm_combo.currentText() == "Mobitz I (Wenckebach)", "panel not synced"

        c.scenario_button.click()
        assert not window.player.running and c.scenario_list.isEnabled()
    finally:
        window.close()


def test_every_state_change_is_logged_whatever_caused_it():
    window, state, _ = live(3.0)
    try:
        window.controls.rhythm_combo.setCurrentText("AFib")     # from the panel
        state.update(resp_pattern="Kussmaul")                   # from elsewhere
        run(window, 1.0)
        log = " | ".join(window.controls.event_log.messages())
        assert "Rhythm: AFib" in log and "Breathing: Kussmaul" in log
    finally:
        window.close()


def test_event_log_is_bounded():
    window = MainWindow()
    try:
        log = window.controls.event_log
        for i in range(log.LIMIT + 50):
            log.add("00:00", f"event {i}")
        assert log.count() == log.LIMIT
        assert log.messages()[0].endswith(f"event {log.LIMIT + 49}"), "newest must be first"
    finally:
        window.close()


def test_every_icon_renders():
    for name in icons.NAMES:
        image = icons.render(name, "#FFFFFF", 24).toImage()
        painted = sum(1 for x in range(image.width()) for y in range(image.height())
                      if image.pixelColor(x, y).alpha() > 0)
        assert painted > 20, f"icon {name!r} is empty"


def test_the_whole_window_stays_responsive_with_the_producer_running():
    state = SimulationState()
    buffer = RingBuffer()
    generator = SignalGenerator(state, buffer)
    window = MainWindow(state.snapshot())
    window.bind(state, buffer, generator)
    window.resize(1480, 900)
    window.show()
    generator.start()
    try:
        worst = 0.0
        deadline = time.perf_counter() + 12.0
        while time.perf_counter() < deadline:
            started = time.perf_counter()
            APP.processEvents()
            window.monitor.refresh()
            APP.processEvents()
            worst = max(worst, time.perf_counter() - started)
            time.sleep(0.02)
        assert buffer.total_written > 10_000, "buffer never filled"
        assert worst < 0.25, f"a frame took {worst * 1000:.0f} ms with the buffer full"
    finally:
        window.close()


if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failures = 0
    for fn in tests:
        try:
            fn()
            print(f"PASS  {fn.__name__}")
        except AssertionError as exc:
            failures += 1
            print(f"FAIL  {fn.__name__}: {exc}")
    print(f"\n{len(tests) - failures}/{len(tests)} passed")
    sys.exit(1 if failures else 0)
